// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkaqf0SXcGh3kAm49x0gwctchGJbzkAMg',
    appId: '1:888650730577:web:3110858f5f1e98f17b7c70',
    messagingSenderId: '888650730577',
    projectId: 'diwage',
    authDomain: 'diwage.firebaseapp.com',
    databaseURL: 'https://diwage-default-rtdb.firebaseio.com',
    storageBucket: 'diwage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIVkqJ4bw4JNI8Y6X7FTXkCnrBwpKrOjY',
    appId: '1:888650730577:android:c61fad3082e984137b7c70',
    messagingSenderId: '888650730577',
    projectId: 'diwage',
    databaseURL: 'https://diwage-default-rtdb.firebaseio.com',
    storageBucket: 'diwage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKhTG9GbP27rXOBQZaOGInrPO4DsS-JHg',
    appId: '1:888650730577:ios:51684111be6624517b7c70',
    messagingSenderId: '888650730577',
    projectId: 'diwage',
    databaseURL: 'https://diwage-default-rtdb.firebaseio.com',
    storageBucket: 'diwage.firebasestorage.app',
    iosClientId: '888650730577-nnv460p2sfdp2o45go01q59qt0kujksn.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailorshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKhTG9GbP27rXOBQZaOGInrPO4DsS-JHg',
    appId: '1:888650730577:ios:51684111be6624517b7c70',
    messagingSenderId: '888650730577',
    projectId: 'diwage',
    databaseURL: 'https://diwage-default-rtdb.firebaseio.com',
    storageBucket: 'diwage.firebasestorage.app',
    iosClientId: '888650730577-nnv460p2sfdp2o45go01q59qt0kujksn.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailorshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF1KgL8zX_y8l5liHr_ti7RShhT1W0miE',
    appId: '1:888650730577:web:04548ea5273adb287b7c70',
    messagingSenderId: '888650730577',
    projectId: 'diwage',
    authDomain: 'diwage.firebaseapp.com',
    databaseURL: 'https://diwage-default-rtdb.firebaseio.com',
    storageBucket: 'diwage.firebasestorage.app',
  );
}
